### PR TITLE
Bump to new cache

### PR DESCRIPTION
**Pull request by ly-kolena**
### Please check if the PR fulfills these requirements

- [ ] Include reference to internal ticket and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Relevant tests for the changes have been added
- [ ] Relevant docs have been added / updated

### CODE REVIEW

**Comment by gordonhart** [comment]
🤔 How did this fix the cache issue?

**Comment by ly-kolena** [comment]
> 🤔 How did this fix the cache issue?

```
      - restore_cache:
          key: &ci-base-cache ci-cache-<< parameters.python-version >>-<< parameters.extras >>-{{ checksum "pyproject.toml" }}
```
checksum changed, so different cache (re-generated)

(This bypass troubleshooting how the previous cache bot corrupted)

**Comment by gordonhart** [comment]
I'm not a huge fan of landing a code change to fix the CircleCI cache.

Is CI caching still necessary? I know that updating our Poetry version to the new parallel installer a few months ago sped setup up by 5x — can we get away with a less complex CI setup?

**Comment by munkyshi** [comment]
A warm cache seems to save ~3 min on total runtime, and ~30 min of machine runtime. 9 min total CI time isn't too bad (though 6 is much nicer). 30 min machine runtime could add up in terms of cost on the CI side of things, but might not be worth it if we have bad caches without a clean way of invalidation.

Do we know why the cache was bad here?

**Comment by yifanwu-kolena** [comment]
[tried to display the env info in CI](https://github.com/kolenaIO/kolena/pull/213) and results are interesting, some of them are valid, some of them are not, even for the same restored cache...

**Comment by gordonhart** [comment]
While the underlying issue of flaky and immutable cache is still there, it's safe to close this PR.

**Pull request closed without merging**
