### PR TITLE
chore: created function to remove result rows greater than 16mb 

### PR DESCRIPTION
**Pull request by brianshen3**
### Linked issue(s)
Towards KOL-7746
### What change does this PR introduce and why?
created function to remove result rows greater than 16mb to fix issues with uploading data that doesn't fit into snowflake limit. And fixed log by adding missing new line.
### Please check if the PR fulfills these requirements

- [ ] Include reference to internal ticket and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Relevant tests for the changes have been added
- [ ] Relevant docs have been added / updated

### CODE REVIEW

**Review by nankolena — COMMENTED** [review]
Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead

**Comment by brianshen3** [comment]
> Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead



> Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead

The issue I am stuck on this with Plus AI. Hamed and the team isn't able to resolve this on their end. I shared with them the code to resolve this but they seem to ignore and choose a code on their end which didn't work. I do think you bring a good point. I will add this as a option to the function call instead of a default run. This would solve the issue with PlusAI and we can have this for future use cases. I will let Hamed know he has that option and the issue is still on his end.

**Comment by nankolena** [comment]
> > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> 
> > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> 
> The issue I am stuck on this with Plus AI. Hamed and the team isn't able to resolve this on their end. I shared with them the code to resolve this but they seem to ignore and choose a code on their end which didn't work. I do think you bring a good point. I will add this as a option to the function call instead of a default run. This would solve the issue with PlusAI and we can have this for future use cases. I will let Hamed know he has that option and the issue is still on his end.

I see, instead of merging this to the public client repo, can we instead sharing this commit if/when we run into this? I'm reluctant having this in the public client repo unless really necessary, and it sounds so far like an edge case

**Comment by brianshen3** [comment]
> > > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> > 
> > 
> > > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> > 
> > 
> > The issue I am stuck on this with Plus AI. Hamed and the team isn't able to resolve this on their end. I shared with them the code to resolve this but they seem to ignore and choose a code on their end which didn't work. I do think you bring a good point. I will add this as a option to the function call instead of a default run. This would solve the issue with PlusAI and we can have this for future use cases. I will let Hamed know he has that option and the issue is still on his end.
> 
> I see, instead of merging this to the public client repo, can we instead sharing this commit if/when we run into this? I'm reluctant having this in the public client repo unless really necessary, and it sounds so far like an edge case

Okay, I will take another approach. I will let Hamed know we decided it was a edge case. I will ask him to share his upload code. I will reiteriate the solution to him again.

**Comment by nankolena** [comment]
> > > > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> > > 
> > > 
> > > > Do we need this? I feel like there's not enough datapoint that warrants the need for this, while it has the potential of failing "silently" if the customer is not paying attention to the logs. My thinking is that we'd want to fail explicitly for now instead
> > > 
> > > 
> > > The issue I am stuck on this with Plus AI. Hamed and the team isn't able to resolve this on their end. I shared with them the code to resolve this but they seem to ignore and choose a code on their end which didn't work. I do think you bring a good point. I will add this as a option to the function call instead of a default run. This would solve the issue with PlusAI and we can have this for future use cases. I will let Hamed know he has that option and the issue is still on his end.
> > 
> > 
> > I see, instead of merging this to the public client repo, can we instead sharing this commit if/when we run into this? I'm reluctant having this in the public client repo unless really necessary, and it sounds so far like an edge case
> 
> Okay, I will take another approach. I will let Hamed know we decided it was a edge case. I will ask him to share his upload code. I will reiteriate the solution to him again.

Sounds good! Sorry for lacking the context here, but feel free to share this code snippet with him too. My perspective is that we should keep an eye on this LOB size usage and if results upload fails we should be aware instead of having them skipped

**Pull request closed without merging**
