### PR TITLE
Add age estimation example integration

### PR DESCRIPTION
**Pull request by gordonhart**
Porting over the [LFW](http://vis-www.cs.umass.edu/lfw/) age estimation demo integration, including automated tests. [Example on app.kolena.io](https://app.kolena.io/sdk-integ/results?modelIds=2&testSuiteId=4&workflow=Age+Estimation&evaluators=N4IgLCBcoExQjAX0UA).

### CODE REVIEW

**Review by ly-kolena — APPROVED** [review]

**Comment by gordonhart** [comment]
Any idea what these `classification` failures are, @ly-kolena? Has been failing consistently on this PR.

**Review by marko-polo-cheno — APPROVED** [review]
LGTM, should we copy over another [readme](https://github.com/kolenaIO/kolena/blob/trunk/examples/text_summarization/README.md) for this example as well?

**Comment by ly-kolena** [comment]
> Any idea what these `classification` failures are, @ly-kolena? Has been failing consistently on this PR.

Looks like I missed this one update to ensure order. Depends on whichever is quicker, you can consider updating `classification.test_test_case.py` the line in `test__create__with_images` from
```
assert images == test_case.load_images()
```
to 
```
 assert_test_images_equal(test_case.load_images(), images)
```

I'll prepare a PR separately if this PR gets green without the change.

**Comment by ly-kolena** [comment]
@gordonhart do you have insight into the failure in detection test? The logic seems changed? The `test__edit__updated` that was marked to be no-op is bumping test-case version.

**Comment by gordonhart** [comment]
Thanks for the pointer @ly-kolena. I've pushed the `classification` fix and am looking into the `detection` flake.

**Pull request merged**
