### PR TITLE
pin pandera<0.16 in examples

### PR DESCRIPTION
**Pull request by sandalns**
### Linked issue(s):
Pin pandera<0.16 for examples.

### Please check if the PR fulfills these requirements

- [ ] Include reference to internal ticket and/or GitHub issue "Fixes #NNNN" (if applicable)
- [ ] Relevant tests for the changes have been added
- [ ] Relevant docs have been added / updated

### CODE REVIEW

**Comment by gordonhart** [comment]
Maybe we should lock these examples such that installs are deterministic. This will prevent us from having to pin transitive dependencies like this. Thoughts @ly-kolena @munkyshi?

**Comment by ly-kolena** [comment]
> Maybe we should lock these examples such that installs are deterministic. This will prevent us from having to pin transitive dependencies like this. Thoughts @ly-kolena @munkyshi?

One concern I have about that is maintenance burden, e.g. keeping track of dependencies of dependencies and version updates.

**Comment by gordonhart** [comment]
The alternative is this maintenance burden, where we need to update every example to pin transitive dependencies in the time between fixing this on `trunk` and releasing the next `kolena` version. This has proven to be non-negligible

**Comment by ly-kolena** [comment]
> The alternative is this maintenance burden, where we need to update every example to pin transitive dependencies in the time between fixing this on `trunk` and releasing the next `kolena` version. This has proven to be non-negligible

We're not shipping examples in `kolena` package. It would be comparatively easy to fix up the versions for later users. For those who already used them to clone their project likely can manage on their own.

I'm not tipped over to take the maintenance burden yet, but not very strongly against it.

**Review by ly-kolena — APPROVED** [review]

**Pull request merged**
