### PR TITLE
Add experimental prebuilt Instance Segmentation workflow

### PR DESCRIPTION
**Pull request by consoull**
### Linked issue(s):
Closes KOL-3869

### What change does this PR introduce and why?
Adds an experimental Instance Segmentation workflow based off of the
experimental Object Detection workflow. The primary difference is that
Instance Segmentation deals with Polygons while Object Detection deals
with Bounding Boxes.

### Please check if the PR fulfills these requirements

- [x] Include reference to internal ticket and/or GitHub issue "Fixes #NNNN" (if applicable)
- [x] Relevant tests for the changes have been added
- [x] Relevant docs have been added / updated

### CODE REVIEW

**Comment by gordonhart** [comment]
Can we make this without copying over a bunch of code from `kolena._experimental.object_detection`? Should be able to just redefine `workflow.py` with polygons, then import everything else from OD. Some minor type changes may be required, but that will make it much much easier to maintain, and reduce the diff here down to a few hundred lines at most.

**Comment by y27choi** [comment]
> Can we make this without copying over a bunch of code from `kolena._experimental.object_detection`? Should be able to just redefine `workflow.py` with polygons, then import everything else from OD. Some minor type changes may be required, but that will make it much much easier to maintain, and reduce the diff here down to a few hundred lines at most.

There is already an [open PR](https://github.com/kolenaIO/kolena/pull/225) for adding polygon support to our pre-built OD workflow which was put on hold due to an API change.

**Comment by gordonhart** [comment]
> There is already an open PR for adding polygon support to our pre-built OD workflow which was put on hold due to an API change.

What I have in mind is the middle ground between this PR and the other PR:

1. Add a new `kolena._experimental.instance_segmentation` workflow
2. Update internal definitions in `object_detection` (evaluator, utils) to accommodate bounding box or polygon geometry
3. Share this polymorphic evaluator implementation between `object_detection` and `instance_segmentation`, removing the need to copy/paste lots of complicated code and tests

This achieves the objectives of adding IS without breaking the API, and reusing as much code as possible.

**Comment by consoull** [comment]
Where is the breaking API change in https://github.com/kolenaIO/kolena/pull/225?

**Comment by gordonhart** [comment]
Renaming `bboxes` to `objects` in [`workflow.py`](https://github.com/kolenaIO/kolena/pull/225/files#diff-8abe933b3194970f1a4e03a8da5f0439a6499a65e092df92dddf5d03b572c9e0R55).

**Comment by consoull** [comment]
Closed in favour of https://github.com/kolenaIO/kolena/pull/225

**Pull request closed without merging**
